# Generated by Django 3.1.1 on 2020-09-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginDetails',
        ),
    ]
