# Generated by Django 3.1.1 on 2020-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_series_name', models.CharField(max_length=200)),
                ('update_type', models.CharField(choices=[('M', 'Monthly'), ('N', 'No Updates'), ('D', 'Daily'), ('W', 'Weekly'), ('H', '6 Months'), ('Y', 'Yearly')], max_length=1)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
