# Generated by Django 3.1.1 on 2020-09-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='UserTvSeries',
        ),
    ]
