# Generated by Django 3.1.1 on 2020-09-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200926_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTvSeries',
        ),
    ]
