# Generated by Django 3.1.1 on 2020-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200929_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertvseriesmodel',
            name='tv_series_name',
            field=models.CharField(default='Not Added', max_length=1023),
        ),
    ]
