# Generated by Django 3.1.1 on 2020-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_usertvseriesmodel_tv_series_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSeriesDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_series_id', models.CharField(max_length=1023)),
                ('tv_series_name', models.CharField(max_length=1023)),
                ('latest_episode_name', models.CharField(max_length=1023)),
                ('latest_episode_number', models.IntegerField()),
                ('release_date', models.CharField(max_length=1023)),
                ('latest_plot', models.TextField()),
                ('announcement_season', models.IntegerField()),
                ('announced_season_total_episode', models.IntegerField()),
            ],
        ),
    ]
