# Generated by Django 3.1.1 on 2020-10-07 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tvseriesdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertvseriesmodel',
            name='last_email_sent',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
