# Generated by Django 3.1.1 on 2020-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_usertvseriesmodel_last_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesdetailsmodel',
            name='tv_series_id',
            field=models.CharField(max_length=1023, unique=True),
        ),
    ]
