# Generated by Django 3.1.1 on 2020-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201007_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseriesdetailsmodel',
            name='announced_season_total_episode',
        ),
        migrations.RemoveField(
            model_name='tvseriesdetailsmodel',
            name='announcement_season',
        ),
        migrations.RemoveField(
            model_name='tvseriesdetailsmodel',
            name='latest_episode_name',
        ),
        migrations.RemoveField(
            model_name='tvseriesdetailsmodel',
            name='latest_episode_number',
        ),
        migrations.RemoveField(
            model_name='tvseriesdetailsmodel',
            name='latest_plot',
        ),
        migrations.RemoveField(
            model_name='tvseriesdetailsmodel',
            name='release_date',
        ),
        migrations.AddField(
            model_name='tvseriesdetailsmodel',
            name='email_body',
            field=models.TextField(default='Tv Series Details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseriesdetailsmodel',
            name='email_subject',
            field=models.TextField(default='Tv Series Details'),
            preserve_default=False,
        ),
    ]
